Update nms_wrapper.py
Changes in nms_wrapper.py facing the error of: InternalError:Failed to run py callback pyfunc_1 to Problem with Proposal_layer : TypeError: 'NoneType' object has no attribute 'getitem, for CPU use